name: example
description: "Floating widget example implementation widget" 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter 
  shared_preferences: ^2.2.2
  floating_logger:
    path: ..
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  google_fonts: 6.2.1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0 
flutter: 
  uses-material-design: true 