name: floating_logger
description: floating_logger is a Flutter library that provides a floating widget for real-time API request logs.

version: 2.1.1
homepage: https://github.com/dzikrul1616/flutter_floating_logger
repository: https://github.com/dzikrul1616/flutter_floating_logger
issue_tracker: https://github.com/dzikrul1616/flutter_floating_logger/issues

topics:
  - dio
  - logger 
  - floating

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  google_fonts: ^6.2.1 
  flutter:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4 
  fake_async: ^1.1.1
  
screenshots:
  - description: Floating logger package logo.
    path: screenshots/logo.png